global proc shelf_test_dev () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;


    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "import sys, os\nimport maya.cmds as cmds\n\nfrom pprint import pprint\n\n\nfor name, path in os.environ.items():\n    \n    if 'MAYA_SHELF_PATH' in name:\n        print(name, path)\n\n" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "import sys, os\nimport maya.cmds as cmds\n\nfrom pprint import ppri..." 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -imageOverlayLabel "find_path" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "pythonFamily.png" 
        -image1 "pythonFamily.png" 
        -style "iconOnly" 
        -marginWidth 1
        -marginHeight 1
        -command "import sys, os\nimport maya.cmds as cmds\n\nfrom pprint import pprint\n\n\nfor name, path in os.environ.items():\n    \n    if 'MAYA_SHELF_PATH' in name:\n        print(name, path)\n\n" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;

} 
